name: React CI/CD Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out our code (clone our code)
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Print debug info
        run: |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          echo "Working Directory: $(pwd)"
          echo "Directory Contents: $(ls -l)"
          echo "node_modules: $(ls -l node_modules)"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out our code (clone our code)
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel env info
        run: vercel pull --yes --environment=preview --token${{ secrets.VERCEL_TOKEN }}
      - name: Vercel Build 
        run: vercel build --token${{ secrets.VERCEL_TOKEN }}
      - name: Vercel Deployment
        run: vercel deploy --prebuilt --token${{ secrets.VERCEL_TOKEN }}